### ISSUE TITLE
fails to build with aeson-1.2.2.0

### ISSUE THREAD

**Issue by juhp** [haskell-miso/miso#295]
See fpco/stackage#2879

```
Building library for miso-0.7.7.0..
[ 1 of 17] Compiling Miso.Concurrent  ( src/Miso/Concurrent.hs, dist/build/Miso/Concurrent.o )
:
[ 7 of 17] Compiling Miso.Html.Internal ( ghc-src/Miso/Html/Internal.hs, dist/build/Miso/Html/Internal.o )

ghc-src/Miso/Html/Internal.hs:202:7: error:
    Ambiguous occurrence ‘Options’
    It could refer to either ‘Data.Aeson.Options’,
                             imported from ‘Data.Aeson’ at ghc-src/Miso/Html/Internal.hs:45:1-27
                             (and originally defined in ‘aeson-1.2.2.0:Data.Aeson.Types.Internal’)
                          or ‘Miso.Event.Options’,
                             imported from ‘Miso.Event’ at ghc-src/Miso/Html/Internal.hs:56:1-27
                             (and originally defined in ‘Miso.Event.Types’
                                at src/Miso/Event/Types.hs:(31,1)-(34,32))
    |
202 |    :: Options
    |       ^^^^^^^
```

**Comment by dmjio** [comment]
@juhp, thanks. Should be fixed in `0.7.8.0` https://github.com/haskell-miso/miso/commit/85a876ffbe68a76be2c152dc3e2573d38db5492f
